// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Enhances chatbot responses to be polite, helpful, and tailored to the specific customer query.
 *
 * - enhanceChatbotResponse - A function that enhances the chatbot response.
 * - EnhanceChatbotResponseInput - The input type for the enhanceChatbotResponse function.
 * - EnhanceChatbotResponseOutput - The return type for the enhanceChatbotResponse function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const EnhanceChatbotResponseInputSchema = z.object({
  customerQuery: z.string().describe('The query from the customer.'),
  chatbotResponse: z.string().describe('The original chatbot response.'),
});
export type EnhanceChatbotResponseInput = z.infer<
  typeof EnhanceChatbotResponseInputSchema
>;

const EnhanceChatbotResponseOutputSchema = z.object({
  enhancedResponse: z.string().describe('The enhanced chatbot response.'),
});
export type EnhanceChatbotResponseOutput = z.infer<
  typeof EnhanceChatbotResponseOutputSchema
>;

export async function enhanceChatbotResponse(
  input: EnhanceChatbotResponseInput
): Promise<EnhanceChatbotResponseOutput> {
  return enhanceChatbotResponseFlow(input);
}

const prompt = ai.definePrompt({
  name: 'enhanceChatbotResponsePrompt',
  input: {schema: EnhanceChatbotResponseInputSchema},
  output: {schema: EnhanceChatbotResponseOutputSchema},
  prompt: `You are an AI assistant designed to enhance chatbot responses to be more polite, helpful, and tailored to the customer query.

  Customer Query: {{{customerQuery}}}
  Chatbot Response: {{{chatbotResponse}}}

  Please enhance the Chatbot Response to be more polite, helpful, and tailored to the specific customer query. The enhanced response should be concise and easy to understand.
  `,
});

const enhanceChatbotResponseFlow = ai.defineFlow(
  {
    name: 'enhanceChatbotResponseFlow',
    inputSchema: EnhanceChatbotResponseInputSchema,
    outputSchema: EnhanceChatbotResponseOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
